# Generated by Django 5.1.6 on 2025-03-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='email',
            new_name='user_email',
        ),
    ]
